name: brainglobe-environment
channels:
  - conda-forge
dependencies:
  - pip=23.1.2
  - python=3.10.11
  - pip:
      - bg-atlasapi==1.0.2
      - bg-space==0.6.0
      - black==23.3.0
      - brainglobe-napari-io==0.1.5
      - brainreg==0.4.0
      - brainreg-napari==0.1.1
      - brainreg-segment==0.2.16
      - cellfinder==0.4.21
      - cellfinder-core==0.4.0
      - cellfinder-napari==0.0.20
      - certifi==2023.5.7
      - coverage==7.2.7
      - jupyterlab==4.0.1
      - mypy==1.3.0
      - napari==0.4.17
      - pyqt5==5.15.9
      - pytest==7.3.1
      - pytest-cov==4.1.0
      - ruff==0.0.270
      - sphinx==4.5.0
      - tox==4.5.2
